spring.application.name=lista-compras-api

# Mudando de localhost para a URL de conexão do Supabase
spring.datasource.url=jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:5432/postgres?sslmode=require

# No username, você vai colar o usuário que o Supabase te deu na URI (geralmente começa com postgres. seguido por letras e números)
spring.datasource.username=postgres.zprsqwynsfyzuphbnkjr

# No password, coloque a senha forte que você definiu ao criar o banco no Supabase
spring.datasource.password=oNiKxgwMAYJ5Papw

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Adiciona essa linha abaixo para avisar o Spring que o dialeto agora é o PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}